[2023-08-16T07:06:20.386+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.is_forex_currencies_file_available manual__2023-08-16T07:06:17.334696+00:00 [queued]>
[2023-08-16T07:06:20.398+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.is_forex_currencies_file_available manual__2023-08-16T07:06:17.334696+00:00 [queued]>
[2023-08-16T07:06:20.398+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T07:06:20.399+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-08-16T07:06:20.399+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T07:06:20.413+0000] {taskinstance.py:1300} INFO - Executing <Task(FileSensor): is_forex_currencies_file_available> on 2023-08-16 07:06:17.334696+00:00
[2023-08-16T07:06:20.418+0000] {standard_task_runner.py:55} INFO - Started process 4891 to run task
[2023-08-16T07:06:20.421+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'forex_data_pipeline', 'is_forex_currencies_file_available', 'manual__2023-08-16T07:06:17.334696+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/forex_data_pipeline.py', '--cfg-path', '/tmp/tmp77m637fl']
[2023-08-16T07:06:20.421+0000] {standard_task_runner.py:83} INFO - Job 35: Subtask is_forex_currencies_file_available
[2023-08-16T07:06:20.483+0000] {task_command.py:388} INFO - Running <TaskInstance: forex_data_pipeline.is_forex_currencies_file_available manual__2023-08-16T07:06:17.334696+00:00 [running]> on host 2761a966e4c6
[2023-08-16T07:06:20.549+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@localhost.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=forex_data_pipeline
AIRFLOW_CTX_TASK_ID=is_forex_currencies_file_available
AIRFLOW_CTX_EXECUTION_DATE=2023-08-16T07:06:17.334696+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-16T07:06:17.334696+00:00
[2023-08-16T07:06:20.557+0000] {base.py:73} INFO - Using connection ID 'forex_path' for task execution.
[2023-08-16T07:06:20.558+0000] {filesystem.py:64} INFO - Poking for file usr/local/***/dags/files/forex_currencies.csv
[2023-08-16T07:06:25.569+0000] {base.py:73} INFO - Using connection ID 'forex_path' for task execution.
[2023-08-16T07:06:25.570+0000] {filesystem.py:64} INFO - Poking for file usr/local/***/dags/files/forex_currencies.csv
[2023-08-16T07:06:30.582+0000] {base.py:73} INFO - Using connection ID 'forex_path' for task execution.
[2023-08-16T07:06:30.583+0000] {filesystem.py:64} INFO - Poking for file usr/local/***/dags/files/forex_currencies.csv
[2023-08-16T07:06:35.594+0000] {base.py:73} INFO - Using connection ID 'forex_path' for task execution.
[2023-08-16T07:06:35.595+0000] {filesystem.py:64} INFO - Poking for file usr/local/***/dags/files/forex_currencies.csv
[2023-08-16T07:06:40.606+0000] {base.py:73} INFO - Using connection ID 'forex_path' for task execution.
[2023-08-16T07:06:40.607+0000] {filesystem.py:64} INFO - Poking for file usr/local/***/dags/files/forex_currencies.csv
[2023-08-16T07:06:40.608+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 215, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 20.057685399999173 seconds exceeds the specified timeout of 20.
[2023-08-16T07:06:40.618+0000] {taskinstance.py:1323} INFO - Immediate failure requested. Marking task as FAILED. dag_id=forex_data_pipeline, task_id=is_forex_currencies_file_available, execution_date=20230816T070617, start_date=20230816T070620, end_date=20230816T070640
[2023-08-16T07:06:40.634+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 35 for task is_forex_currencies_file_available (Sensor has timed out; run duration of 20.057685399999173 seconds exceeds the specified timeout of 20.; 4891)
[2023-08-16T07:06:40.645+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-08-16T07:06:40.661+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
