[2023-07-31 12:53:34,135] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: data_dag.fail 2023-07-31T12:52:37.800520+00:00 [queued]>
[2023-07-31 12:53:34,150] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: data_dag.fail 2023-07-31T12:52:37.800520+00:00 [queued]>
[2023-07-31 12:53:34,150] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2023-07-31 12:53:34,150] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2023-07-31 12:53:34,151] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2023-07-31 12:53:34,161] {taskinstance.py:887} INFO - Executing <Task(BashOperator): fail> on 2023-07-31T12:52:37.800520+00:00
[2023-07-31 12:53:34,165] {standard_task_runner.py:53} INFO - Started process 316 to run task
[2023-07-31 12:53:34,213] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: data_dag.fail 2023-07-31T12:52:37.800520+00:00 [running]> 66e47f8f7cf9
[2023-07-31 12:53:34,234] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2023-07-31 12:53:34,235] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpzfzccs_t/failsgn3d0t1
[2023-07-31 12:53:34,235] {bash_operator.py:115} INFO - Running command: 
                valid=31
                if [ $(($valid % 2)) == 1 ]; then
                        exit 1
                else
                        exit 0
                fi
            
[2023-07-31 12:53:34,241] {bash_operator.py:122} INFO - Output:
[2023-07-31 12:53:34,242] {bash_operator.py:130} INFO - Command exited with return code 1
[2023-07-31 12:53:34,250] {taskinstance.py:1128} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2023-07-31 12:53:34,252] {taskinstance.py:1185} INFO - Marking task as FAILED.dag_id=data_dag, task_id=fail, execution_date=20230731T125237, start_date=20230731T125334, end_date=20230731T125334
[2023-07-31 12:53:44,126] {logging_mixin.py:112} INFO - [2023-07-31 12:53:44,126] {local_task_job.py:103} INFO - Task exited with return code 1
