[2023-08-14T06:09:54.726+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_dag.fail scheduled__2023-08-11T00:00:00+00:00 [queued]>
[2023-08-14T06:09:54.736+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_dag.fail scheduled__2023-08-11T00:00:00+00:00 [queued]>
[2023-08-14T06:09:54.737+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-08-14T06:09:54.737+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-08-14T06:09:54.738+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-08-14T06:09:54.754+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): fail> on 2023-08-11 00:00:00+00:00
[2023-08-14T06:09:54.759+0000] {standard_task_runner.py:55} INFO - Started process 2291 to run task
[2023-08-14T06:09:54.762+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_dag', 'fail', 'scheduled__2023-08-11T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/data_dag.py', '--cfg-path', '/tmp/tmp7x80p6ax']
[2023-08-14T06:09:54.763+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask fail
[2023-08-14T06:09:54.779+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:400: DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
  engine_args["encoding"] = conf.get("database", "SQL_ENGINE_ENCODING", fallback="utf-8")

[2023-08-14T06:09:54.837+0000] {task_command.py:388} INFO - Running <TaskInstance: data_dag.fail scheduled__2023-08-11T00:00:00+00:00 [running]> on host 7dfb041806a2
[2023-08-14T06:09:54.919+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_dag
AIRFLOW_CTX_TASK_ID=fail
AIRFLOW_CTX_EXECUTION_DATE=2023-08-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-11T00:00:00+00:00
[2023-08-14T06:09:54.920+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-14T06:09:54.921+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n                valid=11\n                if [ $(($valid % 2)) == 1 ]; then\n                        exit 1\n                else\n                        exit 0\n                fi\n            ']
[2023-08-14T06:09:54.931+0000] {subprocess.py:86} INFO - Output:
[2023-08-14T06:09:54.933+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-14T06:09:54.944+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-14T06:09:54.949+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=data_dag, task_id=fail, execution_date=20230811T000000, start_date=20230814T060954, end_date=20230814T060954
[2023-08-14T06:09:54.971+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task fail (Bash command failed. The command returned a non-zero exit code 1.; 2291)
[2023-08-14T06:09:55.015+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-08-14T06:09:55.034+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
