[2023-07-31 12:53:38,215] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: data_dag.fail 2023-07-25T00:00:00+00:00 [queued]>
[2023-07-31 12:53:38,232] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: data_dag.fail 2023-07-25T00:00:00+00:00 [queued]>
[2023-07-31 12:53:38,233] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2023-07-31 12:53:38,233] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2023-07-31 12:53:38,234] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2023-07-31 12:53:38,245] {taskinstance.py:887} INFO - Executing <Task(BashOperator): fail> on 2023-07-25T00:00:00+00:00
[2023-07-31 12:53:38,249] {standard_task_runner.py:53} INFO - Started process 332 to run task
[2023-07-31 12:53:38,300] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: data_dag.fail 2023-07-25T00:00:00+00:00 [running]> 66e47f8f7cf9
[2023-07-31 12:53:38,322] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2023-07-31 12:53:38,324] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmp9pgsluev/failvii0weq8
[2023-07-31 12:53:38,324] {bash_operator.py:115} INFO - Running command: 
                valid=25
                if [ $(($valid % 2)) == 1 ]; then
                        exit 1
                else
                        exit 0
                fi
            
[2023-07-31 12:53:38,331] {bash_operator.py:122} INFO - Output:
[2023-07-31 12:53:38,332] {bash_operator.py:130} INFO - Command exited with return code 1
[2023-07-31 12:53:38,340] {taskinstance.py:1128} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2023-07-31 12:53:38,341] {taskinstance.py:1185} INFO - Marking task as FAILED.dag_id=data_dag, task_id=fail, execution_date=20230725T000000, start_date=20230731T125338, end_date=20230731T125338
[2023-07-31 12:53:48,203] {logging_mixin.py:112} INFO - [2023-07-31 12:53:48,203] {local_task_job.py:103} INFO - Task exited with return code 1
